import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseBackground } from '../src/api/manifest.js';
import { DRAWN_CATEGORIES, PHOTO_LICENCES, WALLPAPERS, wallpaperById } from '../src/wallpapers.js';

/**
 * The bundled photographs and paintings (plan item M4.5): where each came
 * from, under which licence, and that the credits the image ships say so.
 *
 * The plan's rule is that a bundled picture comes from the MD5 allowlist only,
 * with its source, author, licence, retrieval date and sha256 recorded per
 * file, `LICENSES.md` and `NOTICE` generated from that record, and a test that
 * fails on a file with no entry or a licence off the allowlist. This is that
 * test. The files on disk are held to the catalogue by `wallpapers.test.ts`
 * ("ships nothing the catalogue does not name"); what is held here is that
 * every entry that is not a drawing carries a credit this file can check.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..', '..');
const DIR = join(HERE, '..', 'assets', 'wallpapers');
const PHOTOS = WALLPAPERS.filter((w) => !DRAWN_CATEGORIES.includes(w.category));

/** The sources MD5 allows, and the hosts each licence's pictures may come from. */
const ALLOWLIST: Record<string, readonly string[]> = {
  'nga-open-access': ['api.nga.gov', 'www.nga.gov'],
  'nasa-media': ['images-assets.nasa.gov', 'images.nasa.gov'],
  rijksmuseum: ['data.rijksmuseum.nl', 'www.rijksmuseum.nl', 'iiif.micr.io'],
  'esa-hubble': ['esahubble.org', 'cdn.esahubble.org'],
  'esa-webb': ['esawebb.org', 'cdn.esawebb.org'],
};
/** The licences that ask for a credit shown with the picture: CC BY. */
const ATTRIBUTION = new Set(['esa-hubble', 'esa-webb']);

describe('a bundled photograph or painting', () => {
  it('exists: twenty-eight of them, beside the drawn set', () => {
    expect(PHOTOS).toHaveLength(28);
  });

  it('carries a credit, under a licence on the allowlist, from a host that licence covers', () => {
    expect(Object.keys(PHOTO_LICENCES).sort()).toEqual(Object.keys(ALLOWLIST).sort());
    for (const w of PHOTOS) {
      const credit = w.credit;
      expect(credit, `${w.id} has no credit`).toBeDefined();
      if (credit === undefined) continue;
      expect(Object.keys(ALLOWLIST), `${w.id}'s licence is not on the allowlist`).toContain(credit.licence);
      for (const field of ['title', 'author', 'date'] as const) expect(credit[field].trim(), `${w.id} ${field}`).not.toBe('');
      for (const address of [credit.source, credit.image]) {
        const url = new URL(address);
        expect(url.protocol, `${w.id}: ${address}`).toBe('https:');
        expect(ALLOWLIST[credit.licence], `${w.id}: ${url.host} is not where ${credit.licence} pictures come from`).toContain(url.host);
      }
      expect(credit.retrieved).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(credit.sha256, `${w.id} records the sha256 of what was fetched`).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it('carries the credit its licence asks to be shown, exactly when it asks', () => {
    for (const [key, licence] of Object.entries(PHOTO_LICENCES)) {
      expect('attribution' in licence && licence.attribution === true, key).toBe(ATTRIBUTION.has(key));
    }
    for (const w of PHOTOS) {
      const attribution = w.credit?.attribution;
      if (ATTRIBUTION.has(w.credit!.licence)) expect(attribution?.trim(), `${w.id} names no credit line`).toBeTruthy();
      else expect(attribution, `${w.id} carries a credit line its licence does not ask for`).toBeUndefined();
    }
  });

  it('carries the patches Soft is solved from, and a drawn wallpaper carries neither those nor a credit', () => {
    for (const w of WALLPAPERS) {
      const photo = !DRAWN_CATEGORIES.includes(w.category);
      expect(w.soft !== undefined, `${w.id} soft patches`).toBe(photo);
      expect(w.credit !== undefined, `${w.id} credit`).toBe(photo);
      if (w.soft !== undefined) {
        expect(w.soft.light).toMatch(/^#[0-9A-F]{6}$/);
        expect(w.soft.dark).toMatch(/^#[0-9A-F]{6}$/);
      }
    }
  });

  it('is fetched by the script whose list the catalogue was written from', () => {
    const script = readFileSync(join(ROOT, 'scripts', 'wallpapers', 'photos.mjs'), 'utf8');
    const listed = [...script.matchAll(/^\s+\{ id: '([a-z0-9-]+)', name:/gm)].map((m) => m[1]);
    expect(listed).toEqual(PHOTOS.map((w) => w.id));
    const catalogue = readFileSync(join(HERE, '..', 'src', 'wallpaper-photos.ts'), 'utf8');
    expect(catalogue.startsWith('/**\n * The bundled photographs and paintings (plan item M4.5). GENERATED by')).toBe(true);
  });

  it('is credited in LICENSES.md and NOTICE, as the script wrote them', () => {
    const licences = readFileSync(join(DIR, 'LICENSES.md'), 'utf8');
    const section = /<!-- photos:start -->([\s\S]*)<!-- photos:end -->/.exec(licences)?.[1] ?? '';
    expect(section).toContain('GENERATED by `scripts/wallpapers/photos.mjs`');
    const notice = readFileSync(join(ROOT, 'NOTICE'), 'utf8');
    const noticeSection = /# photos:start([\s\S]*)# photos:end/.exec(notice)?.[1] ?? '';
    for (const licence of Object.values(PHOTO_LICENCES)) expect(section).toContain(licence.terms);
    for (const w of PHOTOS) {
      const credit = w.credit!;
      for (const fact of [`\`${w.id}\``, credit.title, credit.author, credit.source, credit.image, credit.sha256, credit.retrieved]) {
        expect(section, `LICENSES.md does not say ${fact} of ${w.id}`).toContain(fact);
      }
      expect(noticeSection, `NOTICE does not credit ${w.id}`).toContain(`${credit.title}, ${credit.author}, ${credit.date}`);
    }
    // And no line in the section names a picture the catalogue does not ship.
    const named = [...section.matchAll(/\(`([a-z0-9-]+)`\)/g)].map((m) => m[1]);
    expect(named).toEqual(PHOTOS.map((w) => w.id));
  });

  it('ships three files, each at its long edge, for both orientations to crop from', () => {
    const onDisk = new Set(readdirSync(DIR));
    for (const w of PHOTOS) {
      for (const [file, edge] of [[w.thumb, 320], [w.small, 1600], [w.large, 2880]] as const) {
        expect(onDisk.has(file), file).toBe(true);
        expect(file).toContain(`${w.id}-${edge}.`);
      }
    }
  });
});

describe('a photograph on its way to a wall', () => {
  it('carries both focal points and its Soft patches, so the wall solves without a catalogue of its own', () => {
    const photo = PHOTOS[0]!;
    const resolved = parseBackground(JSON.stringify({ type: 'wallpaper', id: photo.id }));
    expect(resolved).toMatchObject({
      type: 'wallpaper',
      id: photo.id,
      focal: photo.focal,
      portraitFocal: photo.portraitFocal,
      soft: photo.soft,
    });
    // Never its credit: that is the admin's to show, not the wall's to carry.
    expect(JSON.stringify(resolved)).not.toContain(photo.credit!.sha256);
  });

  it('adds nothing to a drawn wallpaper, so a wall on one sends the document it always sent', () => {
    const resolved = parseBackground(JSON.stringify({ type: 'wallpaper', id: 'dusk' }));
    expect(Object.keys(resolved ?? {}).sort()).toEqual(['id', 'large', 'small', 'type']);
    expect(wallpaperById('dusk')?.soft).toBeUndefined();
  });

  it('rotates with them: a category of photographs carries each picture’s patches', () => {
    const resolved = parseBackground(JSON.stringify({ type: 'rotation', collection: 'painting', tone: 'light', every: 60 }));
    expect(resolved?.type).toBe('rotation');
    const pictures = resolved?.type === 'rotation' ? resolved.pictures : [];
    expect(pictures.length).toBe(12);
    for (const one of pictures) {
      expect(one.soft, one.id).toBeDefined();
      expect(one.portraitFocal, one.id).toBeDefined();
    }
  });
});
