/**
 * The emoji vocabulary, server-side (D6, plan item P4.2).
 *
 * A module or a catalogue entry names an emoji by **key**, never a code
 * point, so what reaches the manifest and the admin is the same key both
 * renderers agree on. The artwork itself is a curated Twemoji subset under
 * `apps/server/assets/emoji/`, served from `/assets/emoji/<key>.svg` by
 * `http/static.ts` — same-origin, immutably cached, and rule three holds:
 * nothing here fetches anything at runtime.
 *
 * **The two blocks below are transcribed from `apps/display/src/emoji.ts`
 * character for character** and `emoji-parity.test.ts` compares them as text,
 * the seam `glyph-parity.test.ts` already sits at. The display bundle has no
 * bundler and cannot import this file, and a server test cannot import *from*
 * it — two copies of one vocabulary is this project's most repeated bug, and
 * the cure each time is to hold the copies to each other rather than to trust
 * that they agree.
 *
 * `no-emoji.test.ts` no longer scans this file or its consumers: D6
 * (2026-09-24) permits emoji on a browser wall, drawn from this vocabulary as
 * bundled artwork. It still scans `epaper/**` — an e-paper panel draws no
 * emoji, drawn or otherwise, and never will until it has its own 1-bit motifs.
 */

export const EMOJI_KEYS = [
  // Sky and weather conditions.
  'sun',
  'moon-crescent',
  'full-moon',
  'partly-cloudy-day',
  'cloud',
  'sun-behind-large-cloud',
  'sun-behind-rain-cloud',
  'cloud-with-rain',
  'cloud-with-lightning',
  'thunderstorm',
  'cloud-with-snow',
  'snowflake',
  'snowman',
  'snowman-without-snow',
  'fog',
  'wind-face',
  'tornado',
  'rainbow',
  'umbrella-with-rain-drops',
  'droplet',
  'sweat-droplets',
  'thermometer',
  // Advice-line pictures. Umbrella and wind are the weather set's own.
  'wind',
  'coat',
  'shorts',
  'sunscreen',
  // Occasions (D3): the six the countdown widget's occasion picker names.
  'christmas-tree',
  'birthday-cake',
  'jack-o-lantern',
  'beach-umbrella',
  'school-satchel',
  'fireworks',
  // The Store's hourglass (P1.1), and its counterpart.
  'hourglass',
  'hourglass-done',
  // A general picker: celebrations, travel, life events, sport, school, nature, animals and entertainment.
  'party-popper',
  'confetti-ball',
  'balloon',
  'gift',
  'sparkles',
  'star',
  'glowing-star',
  'trophy',
  'medal-1st-place',
  'medal-military',
  'ribbon',
  'red-heart',
  'two-hearts',
  'sparkling-heart',
  'heart-with-arrow',
  'revolving-hearts',
  'shortcake',
  'pizza',
  'popcorn',
  'bottle-with-popping-cork',
  'clinking-glasses',
  'cocktail-glass',
  'hot-beverage',
  'airplane',
  'car',
  'luggage',
  'palm-tree',
  'mountain',
  'camping',
  'ship',
  'world-map',
  'compass',
  'bride-with-veil',
  'ring',
  'baby',
  'baby-bottle',
  'graduation-cap',
  'house',
  'key',
  'briefcase',
  'package',
  'soccer-ball',
  'basketball',
  'american-football',
  'baseball',
  'tennis',
  'volleyball',
  'bowling',
  'books',
  'pencil',
  'leaf-fallen',
  'maple-leaf',
  'cherry-blossom',
  'sunflower',
  'four-leaf-clover',
  'tulip',
  'rose',
  'dog-face',
  'cat-face',
  'rabbit-face',
  'turkey',
  'baby-chick',
  'bird',
  'butterfly',
  'movie-camera',
  'ticket',
  'admission-tickets',
  'musical-note',
  'microphone',
  'video-game',
  'game-die',
  'artist-palette',
  'direct-hit',
  'alarm-clock',
  'calendar',
  'spiral-calendar',
  'white-check-mark',
  'sparkler',
  'candle',
  'light-bulb',
  'partying-face',
  'smiling-face-with-sunglasses',
  'clapping-hands',
  'raised-hands',
  'thumbs-up',
  'muscle',
  'crown',
  'gem-stone',
  'money-bag',
  'dollar-banknote',
  'rocket',
  'earth-globe-americas',
  'sunrise',
  'sunset',
  'star-struck',
  'santa',
  'bell',
  'reindeer',
  'ferris-wheel',
  'roller-coaster',
  'circus-tent',
  'performing-arts',
  'diploma-scroll',
  'credit-card',
  'shopping-bags',
  'high-voltage',
  'cyclone',
  'closed-umbrella',
  'ice-cream',
  'watermelon',
  'sunglasses',
  'apple-fruit',
  'ruler',
  'heart-eyes',
  'gift-heart',
  'handshake',
  'waving-hand',
  'paw-prints',
  'deciduous-tree',
  'evergreen-tree',
  'kiss-mark',
] as const;

export type EmojiKey = (typeof EMOJI_KEYS)[number];

/**
 * Whether a string names a bundled emoji. Used at every boundary a key
 * crosses: a widget's stored config and the store catalogue at build time.
 */
export function isEmojiKey(value: unknown): value is EmojiKey {
  return typeof value === 'string' && (EMOJI_KEYS as readonly string[]).includes(value);
}

const LABELS: Readonly<Record<EmojiKey, string>> = {
  'sun': 'Sun',
  'moon-crescent': 'Crescent moon',
  'full-moon': 'Full moon',
  'partly-cloudy-day': 'Sun behind cloud',
  'cloud': 'Cloud',
  'sun-behind-large-cloud': 'Sun behind large cloud',
  'sun-behind-rain-cloud': 'Sun behind rain cloud',
  'cloud-with-rain': 'Cloud with rain',
  'cloud-with-lightning': 'Cloud with lightning',
  'thunderstorm': 'Thunderstorm',
  'cloud-with-snow': 'Cloud with snow',
  'snowflake': 'Snowflake',
  'snowman': 'Snowman',
  'snowman-without-snow': 'Snowman without snow',
  'fog': 'Fog',
  'wind-face': 'Wind',
  'tornado': 'Tornado',
  'rainbow': 'Rainbow',
  'umbrella-with-rain-drops': 'Umbrella with rain drops',
  'droplet': 'Droplet',
  'sweat-droplets': 'Sweat droplets',
  'thermometer': 'Thermometer',
  'wind': 'Blowing gust',
  'coat': 'Coat',
  'shorts': 'Shorts',
  'sunscreen': 'Sunscreen',
  'christmas-tree': 'Christmas tree',
  'birthday-cake': 'Birthday cake',
  'jack-o-lantern': 'Jack-o-lantern',
  'beach-umbrella': 'Beach with umbrella',
  'school-satchel': 'School satchel',
  'fireworks': 'Fireworks',
  'hourglass': 'Hourglass, not done',
  'hourglass-done': 'Hourglass done',
  'party-popper': 'Party popper',
  'confetti-ball': 'Confetti ball',
  'balloon': 'Balloon',
  'gift': 'Wrapped gift',
  'sparkles': 'Sparkles',
  'star': 'Star',
  'glowing-star': 'Glowing star',
  'trophy': 'Trophy',
  'medal-1st-place': '1st place medal',
  'medal-military': 'Military medal',
  'ribbon': 'Ribbon',
  'red-heart': 'Red heart',
  'two-hearts': 'Two hearts',
  'sparkling-heart': 'Sparkling heart',
  'heart-with-arrow': 'Heart with arrow',
  'revolving-hearts': 'Revolving hearts',
  'shortcake': 'Shortcake',
  'pizza': 'Pizza',
  'popcorn': 'Popcorn',
  'bottle-with-popping-cork': 'Bottle with popping cork',
  'clinking-glasses': 'Clinking glasses',
  'cocktail-glass': 'Cocktail glass',
  'hot-beverage': 'Hot beverage',
  'airplane': 'Airplane',
  'car': 'Car',
  'luggage': 'Luggage',
  'palm-tree': 'Palm tree',
  'mountain': 'Mountain',
  'camping': 'Camping',
  'ship': 'Ship',
  'world-map': 'World map',
  'compass': 'Compass',
  'bride-with-veil': 'Person with veil',
  'ring': 'Ring',
  'baby': 'Baby',
  'baby-bottle': 'Baby bottle',
  'graduation-cap': 'Graduation cap',
  'house': 'House',
  'key': 'Key',
  'briefcase': 'Briefcase',
  'package': 'Package',
  'soccer-ball': 'Soccer ball',
  'basketball': 'Basketball',
  'american-football': 'American football',
  'baseball': 'Baseball',
  'tennis': 'Tennis',
  'volleyball': 'Volleyball',
  'bowling': 'Bowling',
  'books': 'Books',
  'pencil': 'Pencil',
  'leaf-fallen': 'Fallen leaf',
  'maple-leaf': 'Maple leaf',
  'cherry-blossom': 'Cherry blossom',
  'sunflower': 'Sunflower',
  'four-leaf-clover': 'Four leaf clover',
  'tulip': 'Tulip',
  'rose': 'Rose',
  'dog-face': 'Dog face',
  'cat-face': 'Cat face',
  'rabbit-face': 'Rabbit face',
  'turkey': 'Turkey',
  'baby-chick': 'Baby chick',
  'bird': 'Bird',
  'butterfly': 'Butterfly',
  'movie-camera': 'Movie camera',
  'ticket': 'Ticket',
  'admission-tickets': 'Admission tickets',
  'musical-note': 'Musical note',
  'microphone': 'Microphone',
  'video-game': 'Video game',
  'game-die': 'Game die',
  'artist-palette': 'Artist palette',
  'direct-hit': 'Direct hit',
  'alarm-clock': 'Alarm clock',
  'calendar': 'Calendar',
  'spiral-calendar': 'Spiral calendar',
  'white-check-mark': 'Check mark',
  'sparkler': 'Sparkler',
  'candle': 'Candle',
  'light-bulb': 'Light bulb',
  'partying-face': 'Partying face',
  'smiling-face-with-sunglasses': 'Smiling face with sunglasses',
  'clapping-hands': 'Clapping hands',
  'raised-hands': 'Raised hands',
  'thumbs-up': 'Thumbs up',
  'muscle': 'Flexed biceps',
  'crown': 'Crown',
  'gem-stone': 'Gem stone',
  'money-bag': 'Money bag',
  'dollar-banknote': 'Dollar banknote',
  'rocket': 'Rocket',
  'earth-globe-americas': 'Globe showing Americas',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset over buildings',
  'star-struck': 'Star-struck face',
  'santa': 'Santa Claus',
  'bell': 'Bell',
  'reindeer': 'Deer',
  'ferris-wheel': 'Ferris wheel',
  'roller-coaster': 'Roller coaster',
  'circus-tent': 'Circus tent',
  'performing-arts': 'Performing arts',
  'diploma-scroll': 'Scroll',
  'credit-card': 'Credit card',
  'shopping-bags': 'Shopping bags',
  'high-voltage': 'High voltage',
  'cyclone': 'Cyclone',
  'closed-umbrella': 'Closed umbrella',
  'ice-cream': 'Soft ice cream',
  'watermelon': 'Watermelon',
  'sunglasses': 'Sunglasses',
  'apple-fruit': 'Red apple',
  'ruler': 'Straight ruler',
  'heart-eyes': 'Heart eyes face',
  'gift-heart': 'Heart with ribbon',
  'handshake': 'Handshake',
  'waving-hand': 'Waving hand',
  'paw-prints': 'Paw prints',
  'deciduous-tree': 'Deciduous tree',
  'evergreen-tree': 'Evergreen tree',
  'kiss-mark': 'Kiss mark',
};

/**
 * One emoji as an `<img>`, or `''` for a key with no artwork.
 *
 * For the server-rendered admin — the store card today, a designed wall style
 * tomorrow reads this same vocabulary through `emojiNode` instead, because the
 * display bundle builds a node rather than a string (it has no `innerHTML`
 * anywhere). The key is checked against the vocabulary before it is used, so
 * nothing a stranger's catalogue entry named reaches this string unvalidated.
 */
export function emojiImg(key: unknown, className: string): string {
  if (!isEmojiKey(key)) return '';
  return `<img class="${className}" src="/assets/emoji/${key}.svg" alt="${LABELS[key]}">`;
}
