/**
 * The bundled photographs and paintings (plan item M4.5). GENERATED by
 * `scripts/wallpapers/photos.mjs` — edit the list there and run it again; do
 * not edit this file.
 *
 * Every entry names where its picture came from, under which licence, when it
 * was retrieved and the sha256 of the bytes that were fetched; its colour,
 * luminance and Soft patches were measured off the shipped 1600px file, and
 * every file name is the sha256 of the bytes it names.
 */
export const PHOTO_LICENCES = {
  "nga-open-access": {
    "name": "Public domain, National Gallery of Art open access",
    "terms": "https://www.nga.gov/artworks/free-images-and-open-access",
    "statement": "Images of public-domain works, free of charge for any use, whether commercial or non-commercial.",
    "hosts": [
      "api.nga.gov",
      "www.nga.gov"
    ]
  },
  "nasa-media": {
    "name": "Public domain, NASA",
    "terms": "https://www.nasa.gov/nasa-brand-center/images-and-media/",
    "statement": "NASA content is generally not subject to copyright in the United States; credit NASA.",
    "hosts": [
      "images-assets.nasa.gov",
      "images.nasa.gov"
    ]
  }
} as const;

export const WALLPAPER_PHOTOS = /* photos */ [
  {
    "id": "moonlit-bridge",
    "name": "Moonlit landscape",
    "category": "painting",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 52,
      "y": 50
    },
    "color": "#3B3430",
    "luminance": 0.048,
    "thumb": "moonlit-bridge-320.1116331801.jpg",
    "small": "moonlit-bridge-1600.6f7933b8a5.jpg",
    "large": "moonlit-bridge-2880.6d4e65aecf.jpg",
    "soft": {
      "light": "#B9A384",
      "dark": "#141318"
    },
    "credit": {
      "title": "Moonlit Landscape with Bridge",
      "author": "Aert van der Neer",
      "date": "probably 1648/1650",
      "source": "https://www.nga.gov/collection/art-object-page.71369.html",
      "image": "https://api.nga.gov/iiif/642620fe-1a26-4ae8-b93a-a84f8c695b60/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "bb6c901d5834c70191971b14e34cae461aaa9dbaa88eee91ce6a5e431cd3fba1"
    }
  },
  {
    "id": "sunset-woods",
    "name": "Sunset in the woods",
    "category": "painting",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 64,
      "y": 50
    },
    "color": "#3C3122",
    "luminance": 0.037,
    "thumb": "sunset-woods-320.84b47e1f6a.jpg",
    "small": "sunset-woods-1600.c6f06b015b.jpg",
    "large": "sunset-woods-2880.2bec206ed0.jpg",
    "soft": {
      "light": "#D8A745",
      "dark": "#231E1A"
    },
    "credit": {
      "title": "Sunset in the Woods",
      "author": "George Inness",
      "date": "1891",
      "source": "https://www.nga.gov/collection/art-object-page.166496.html",
      "image": "https://api.nga.gov/iiif/ec49c7f7-2438-4522-99cd-8569985c909d/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "b3f1efbf10302d1b5d85819178226d2c0187356bc15a788efc6b866e8c2946f5"
    }
  },
  {
    "id": "river-of-light",
    "name": "River of light",
    "category": "painting",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 50,
      "y": 50
    },
    "color": "#766445",
    "luminance": 0.183,
    "thumb": "river-of-light-320.ab49a8ad3e.jpg",
    "small": "river-of-light-1600.7abb58163c.jpg",
    "large": "river-of-light-2880.0b96075355.jpg",
    "soft": {
      "light": "#F2E2AD",
      "dark": "#1B140A"
    },
    "credit": {
      "title": "El Rio de Luz (The River of Light)",
      "author": "Frederic Edwin Church",
      "date": "1877",
      "source": "https://www.nga.gov/collection/art-object-page.50299.html",
      "image": "https://api.nga.gov/iiif/9d96691b-10b2-44c9-8670-a642e0cd9ce2/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "d9ae989059de5a3663909f72262fabdb93f19dc9a654ab9705c2b985b2d8c066"
    }
  },
  {
    "id": "impending-storm",
    "name": "Impending storm",
    "category": "painting",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 45
    },
    "portraitFocal": {
      "x": 45,
      "y": 50
    },
    "color": "#5B5A4F",
    "luminance": 0.148,
    "thumb": "impending-storm-320.2152c388ff.jpg",
    "small": "impending-storm-1600.04cc9a3c1b.jpg",
    "large": "impending-storm-2880.dd305b4dcb.jpg",
    "soft": {
      "light": "#EFEAC6",
      "dark": "#21161A"
    },
    "credit": {
      "title": "Buffalo Trail: The Impending Storm",
      "author": "Albert Bierstadt",
      "date": "1869",
      "source": "https://www.nga.gov/collection/art-object-page.166427.html",
      "image": "https://api.nga.gov/iiif/8681fef5-68c8-4449-9a71-4722f0bc2899/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "2f20f6d5ac068cff9e42772d58df4afe272ae9e817560e4af870ceb4da272375"
    }
  },
  {
    "id": "keelmen",
    "name": "Keelmen by moonlight",
    "category": "painting",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 42,
      "y": 50
    },
    "color": "#8D9382",
    "luminance": 0.32,
    "thumb": "keelmen-320.1c80858be1.jpg",
    "small": "keelmen-1600.765fd85c36.jpg",
    "large": "keelmen-2880.66b4b694aa.jpg",
    "soft": {
      "light": "#F5EBCA",
      "dark": "#1B1B11"
    },
    "credit": {
      "title": "Keelmen Heaving in Coals by Moonlight",
      "author": "Joseph Mallord William Turner",
      "date": "1835",
      "source": "https://www.nga.gov/collection/art-object-page.1225.html",
      "image": "https://api.nga.gov/iiif/c1e33e8d-ffe4-4d20-a267-87ffcf94f7ce/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "c132db99de294fbf63f78ea66ccf01366e874e5dcc9346da75afda965b66e724"
    }
  },
  {
    "id": "parliament",
    "name": "Parliament at sunset",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 45
    },
    "portraitFocal": {
      "x": 48,
      "y": 50
    },
    "color": "#91999A",
    "luminance": 0.331,
    "thumb": "parliament-320.16979f2435.jpg",
    "small": "parliament-1600.3189cc6a38.jpg",
    "large": "parliament-2880.0169fe14ac.jpg",
    "soft": {
      "light": "#CFC7A9",
      "dark": "#4C6C89"
    },
    "credit": {
      "title": "The Houses of Parliament, Sunset",
      "author": "Claude Monet",
      "date": "1903",
      "source": "https://www.nga.gov/collection/art-object-page.46523.html",
      "image": "https://api.nga.gov/iiif/9eae6258-ec1c-442f-b353-a89cff510113/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "8f91a52773cbd54345dbf8b3c0fdde335957307c3bfc2bebcfb101daf72258f9"
    }
  },
  {
    "id": "waterloo-bridge",
    "name": "Waterloo Bridge",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 40,
      "y": 50
    },
    "color": "#ACB4B5",
    "luminance": 0.452,
    "thumb": "waterloo-bridge-320.05ed26f4a8.jpg",
    "small": "waterloo-bridge-1600.8948e35b35.jpg",
    "large": "waterloo-bridge-2880.bc88dd91f8.jpg",
    "soft": {
      "light": "#CDD6DD",
      "dark": "#88989D"
    },
    "credit": {
      "title": "Waterloo Bridge, London, at Sunset",
      "author": "Claude Monet",
      "date": "1904",
      "source": "https://www.nga.gov/collection/art-object-page.61378.html",
      "image": "https://api.nga.gov/iiif/e5c0853d-e3ac-49c2-884e-c0ac3b0af597/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "e70ccea8a3778c9959c0855b328ea1702d0969a9fb966edf25ce259e739d316d"
    }
  },
  {
    "id": "vetheuil-garden",
    "name": "Garden at Vétheuil",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 45
    },
    "portraitFocal": {
      "x": 50,
      "y": 50
    },
    "color": "#88927D",
    "luminance": 0.3,
    "thumb": "vetheuil-garden-320.b57ee7bddb.jpg",
    "small": "vetheuil-garden-1600.196061f812.jpg",
    "large": "vetheuil-garden-2880.5e14012972.jpg",
    "soft": {
      "light": "#F0C896",
      "dark": "#284E39"
    },
    "credit": {
      "title": "The Artist's Garden at Vétheuil",
      "author": "Claude Monet",
      "date": "1881",
      "source": "https://www.nga.gov/collection/art-object-page.52189.html",
      "image": "https://api.nga.gov/iiif/9fc88734-2f9a-4da8-8d46-2b570b201223/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "c2ec13251817436ad5c3807c36b9e41f09cdd111ae2d74f12a739301f5a6b613"
    }
  },
  {
    "id": "meadow",
    "name": "Meadow",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 50,
      "y": 50
    },
    "color": "#849A7C",
    "luminance": 0.317,
    "thumb": "meadow-320.037ad5186f.jpg",
    "small": "meadow-1600.38689db454.jpg",
    "large": "meadow-2880.17bb17d35a.jpg",
    "soft": {
      "light": "#D6CCAC",
      "dark": "#183D32"
    },
    "credit": {
      "title": "Meadow",
      "author": "Alfred Sisley",
      "date": "1875",
      "source": "https://www.nga.gov/collection/art-object-page.52227.html",
      "image": "https://api.nga.gov/iiif/1c2440bb-63a8-434b-8cd9-8307226aa917/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "bc1d40a5ca17c20deea7dca9d42f3c976a796c30091ba1f23c6a48c9cc92edac"
    }
  },
  {
    "id": "port-en-bessin",
    "name": "Port-en-Bessin",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 55,
      "y": 50
    },
    "color": "#969473",
    "luminance": 0.334,
    "thumb": "port-en-bessin-320.6ea1d1c617.jpg",
    "small": "port-en-bessin-1600.30fe50f033.jpg",
    "large": "port-en-bessin-2880.6e4ea9b462.jpg",
    "soft": {
      "light": "#EBD4A9",
      "dark": "#343321"
    },
    "credit": {
      "title": "Seascape at Port-en-Bessin, Normandy",
      "author": "Georges Seurat",
      "date": "1888",
      "source": "https://www.nga.gov/collection/art-object-page.53139.html",
      "image": "https://api.nga.gov/iiif/f395c5e5-6711-487e-8c1b-747c698d1ef9/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "16f51bf38cc37a0a2ccb18b88ff677becd1e4a06700d0f5a277a1958a9d8d0e3"
    }
  },
  {
    "id": "eragny-garden",
    "name": "Garden at Eragny",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 45
    },
    "portraitFocal": {
      "x": 50,
      "y": 50
    },
    "color": "#8A907A",
    "luminance": 0.319,
    "thumb": "eragny-garden-320.d9457b9de2.jpg",
    "small": "eragny-garden-1600.187f4341d3.jpg",
    "large": "eragny-garden-2880.468c71bc69.jpg",
    "soft": {
      "light": "#E8E8DC",
      "dark": "#313F35"
    },
    "credit": {
      "title": "The Artist's Garden at Eragny",
      "author": "Camille Pissarro",
      "date": "1898",
      "source": "https://www.nga.gov/collection/art-object-page.52198.html",
      "image": "https://api.nga.gov/iiif/e291058c-0769-493c-a5f3-8e0e64e9ea46/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "ad3670b706d3c0dce0aa725ef09a0de4b90a2e931db55919df56d32fbd9f4e65"
    }
  },
  {
    "id": "cloud-study",
    "name": "Cloud study",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 40
    },
    "portraitFocal": {
      "x": 50,
      "y": 50
    },
    "color": "#A99F8E",
    "luminance": 0.367,
    "thumb": "cloud-study-320.c6dde5a713.jpg",
    "small": "cloud-study-1600.4b99f7c4da.jpg",
    "large": "cloud-study-2880.c1831141e2.jpg",
    "soft": {
      "light": "#E7DDBF",
      "dark": "#8C6359"
    },
    "credit": {
      "title": "Cloud Study: Stormy Sunset",
      "author": "John Constable",
      "date": "1821-1822",
      "source": "https://www.nga.gov/collection/art-object-page.104243.html",
      "image": "https://api.nga.gov/iiif/83544e9a-2499-4d42-aeb1-62dbc2c2392b/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "018a2661b5424f42200b5c655bc6c2deb964f520ad81be0e67309f7e46cef315"
    }
  },
  {
    "id": "beacon-rock",
    "name": "Beacon Rock",
    "category": "painting",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 62,
      "y": 50
    },
    "color": "#7D8265",
    "luminance": 0.26,
    "thumb": "beacon-rock-320.f03c79fada.jpg",
    "small": "beacon-rock-1600.fa08e0aea4.jpg",
    "large": "beacon-rock-2880.57dfdc3468.jpg",
    "soft": {
      "light": "#C1C69B",
      "dark": "#311F13"
    },
    "credit": {
      "title": "Beacon Rock, Newport Harbor",
      "author": "John Frederick Kensett",
      "date": "1857",
      "source": "https://www.nga.gov/collection/art-object-page.42389.html",
      "image": "https://api.nga.gov/iiif/c31769b8-f5f8-41bd-b204-1e838690c219/full/!3200,3200/0/default.jpg",
      "licence": "nga-open-access",
      "retrieved": "2026-10-10",
      "sha256": "43d1277fee13f4ecab293f0501a7c4acce320b9a53b0d2d26ae0875e0818f2b9"
    }
  },
  {
    "id": "orbital-sunset",
    "name": "Sunset from orbit",
    "category": "space",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 50
    },
    "portraitFocal": {
      "x": 60,
      "y": 50
    },
    "color": "#3B454E",
    "luminance": 0.144,
    "thumb": "orbital-sunset-320.3d99c1f64d.jpg",
    "small": "orbital-sunset-1600.6c6a4363d0.jpg",
    "large": "orbital-sunset-2880.112334c3c6.jpg",
    "soft": {
      "light": "#D0EAF1",
      "dark": "#030408"
    },
    "credit": {
      "title": "The sun peeking over the limb of the Earth (ISS028-E-007274)",
      "author": "NASA, Expedition 28 crew",
      "date": "11 June 2011",
      "source": "https://images.nasa.gov/details/iss028e007274",
      "image": "https://images-assets.nasa.gov/image/iss028e007274/iss028e007274~orig.jpg",
      "licence": "nasa-media",
      "retrieved": "2026-10-10",
      "sha256": "5a747caba29780f6c2925a641178abe6066e4f72fbaac8b2b4d0d40470203ad6"
    }
  },
  {
    "id": "green-aurora",
    "name": "Aurora from orbit",
    "category": "space",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 55
    },
    "portraitFocal": {
      "x": 50,
      "y": 50
    },
    "color": "#3D413C",
    "luminance": 0.098,
    "thumb": "green-aurora-320.d5460dc83c.jpg",
    "small": "green-aurora-1600.c68c97ae18.jpg",
    "large": "green-aurora-2880.8e466e8599.jpg",
    "soft": {
      "light": "#BFEC74",
      "dark": "#0F0E0D"
    },
    "credit": {
      "title": "A bright green aurora borealis streams above Earth's surface (iss072e188141)",
      "author": "NASA astronaut Nick Hague",
      "date": "15 November 2024",
      "source": "https://images.nasa.gov/details/iss072e188141",
      "image": "https://images-assets.nasa.gov/image/iss072e188141/iss072e188141~orig.jpg",
      "licence": "nasa-media",
      "retrieved": "2026-10-10",
      "sha256": "24cb9931aa8085f946dc26427a3fc41f8dcb02f06bea1389db4783a32a0109e9"
    }
  },
  {
    "id": "night-lights",
    "name": "Night lights and aurora",
    "category": "space",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 85
    },
    "portraitFocal": {
      "x": 55,
      "y": 50
    },
    "color": "#231A12",
    "luminance": 0.03,
    "thumb": "night-lights-320.69fcdbecf9.jpg",
    "small": "night-lights-1600.da9dcfb54f.jpg",
    "large": "night-lights-2880.e70a0b580e.jpg",
    "soft": {
      "light": "#F0D5C0",
      "dark": "#030103"
    },
    "credit": {
      "title": "Aurora borealis and city lights on the horizon (ISS029-E-012564)",
      "author": "NASA astronaut Mike Fossum",
      "date": "29 September 2011",
      "source": "https://images.nasa.gov/details/iss029e012564",
      "image": "https://images-assets.nasa.gov/image/iss029e012564/iss029e012564~orig.jpg",
      "licence": "nasa-media",
      "retrieved": "2026-10-10",
      "sha256": "287ec766c4efdc00d72eb8c80070358ebb95d6903659086814200ff854a8bca5"
    }
  }
] as const;
