/**
 * What each bundled wallpaper shows through Glass (plan item M4.2): its lightest
 * and darkest patch, blurred and saturated as Glass draws it. GENERATED by
 * `scripts/wallpapers/glass.mjs` from the shipped 1600px files — run it again
 * after the pictures change; do not edit this file. `file` is the content-hashed
 * name it was measured from, so `browser-wallpaper-glass.test.ts` knows at once
 * when a picture has been redrawn and this has not.
 */
export const WALLPAPER_GLASS: Readonly<Record<string, { readonly file: string; readonly light: string; readonly dark: string }>> = {
  'dusk': { file: 'dusk-1600.8cdf4d0b6d.jpg', light: '#4B355B', dark: '#121A35' },
  'midnight': { file: 'midnight-1600.52f7fc420c.jpg', light: '#192855', dark: '#0C1025' },
  'ember': { file: 'ember-1600.3e98f48925.jpg', light: '#5F2B15', dark: '#201412' },
  'deep-sea': { file: 'deep-sea-1600.864dd2837d.jpg', light: '#084A58', dark: '#051F29' },
  'dawn-haze': { file: 'dawn-haze-1600.7ddca122f5.jpg', light: '#F4E6E3', dark: '#F0DED0' },
  'mist': { file: 'mist-1600.b165d6b60b.jpg', light: '#EAEFF2', dark: '#D9E0E6' },
  'paper': { file: 'paper-1600.4c3416b353.jpg', light: '#F6F0E3', dark: '#EBE3D1' },
  'linen': { file: 'linen-1600.85ca5caa4d.jpg', light: '#EEE5D7', dark: '#E3DBC7' },
  'watercolour': { file: 'watercolour-1600.6eefc7970f.jpg', light: '#F5EEE2', dark: '#D2D1C3' },
  'plaster': { file: 'plaster-1600.4bc1c1efd7.jpg', light: '#ECE6DD', dark: '#E0DCD2' },
  'contours': { file: 'contours-1600.86ec20bc74.jpg', light: '#252C39', dark: '#161C27' },
  'charted': { file: 'charted-1600.89f27b93e4.jpg', light: '#282D24', dark: '#19221C' },
  'survey': { file: 'survey-1600.b416f0d364.jpg', light: '#F1EBDE', dark: '#DDD7CA' },
  'bauhaus': { file: 'bauhaus-1600.d4932125b3.jpg', light: '#88804D', dark: '#1D1E24' },
  'terrazzo': { file: 'terrazzo-1600.fcb924f705.jpg', light: '#EFE8DF', dark: '#D3C6CA' },
  'grid': { file: 'grid-1600.e155b0f730.jpg', light: '#1F324E', dark: '#161A24' },
  'hills': { file: 'hills-1600.31acbd34ed.jpg', light: '#1C3932', dark: '#0F201D' },
  'dunes': { file: 'dunes-1600.9ee922de6f.jpg', light: '#F0E8D7', dark: '#DEC7A4' },
  'dawn-sky': { file: 'dawn-sky-1600.a7f33a4bff.jpg', light: '#F8EDDD', dark: '#F5DABF' },
  'dusk-sky': { file: 'dusk-sky-1600.6c7b26d07f.jpg', light: '#7B3A41', dark: '#0F0B14' },
  'autumn': { file: 'autumn-1600.9ee2413c49.jpg', light: '#663E15', dark: '#1D1610' },
  'winter': { file: 'winter-1600.9735495d1f.jpg', light: '#E4EBF4', dark: '#D3E0E9' },
  'spring': { file: 'spring-1600.a8e579157c.jpg', light: '#F4F0E3', dark: '#E6C7C5' },
  'summer': { file: 'summer-1600.5d6bcc7039.jpg', light: '#B47E2A', dark: '#032A3B' },
  'confetti': { file: 'confetti-1600.99b84e130e.jpg', light: '#4B3B25', dark: '#151322' },
  'night-sky': { file: 'night-sky-1600.985787cc34.jpg', light: '#212A54', dark: '#080C21' },
};
