/**
 * The wallpaper catalogue (plan item P6.2). GENERATED by
 * `scripts/wallpapers/generate.mjs` — edit the drawing or the seed there and
 * run it again; do not edit this file.
 *
 * Every colour and luminance here was measured off the rendered picture, and
 * every file name is the sha256 of the bytes it names.
 */
export const WALLPAPER_CATALOGUE = /* catalogue */ [
  {
    "id": "dusk",
    "name": "Dusk",
    "category": "gradient",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#2A2842",
    "luminance": 0.026,
    "thumb": "dusk-320.96e141ee69.jpg",
    "small": "dusk-1600.8cdf4d0b6d.jpg",
    "large": "dusk-2880.3c3cb90dbb.jpg"
  },
  {
    "id": "midnight",
    "name": "Midnight",
    "category": "gradient",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#151B30",
    "luminance": 0.012,
    "thumb": "midnight-320.3ebc0b9585.jpg",
    "small": "midnight-1600.52f7fc420c.jpg",
    "large": "midnight-2880.e6495d4cda.jpg"
  },
  {
    "id": "ember",
    "name": "Ember",
    "category": "gradient",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#362119",
    "luminance": 0.02,
    "thumb": "ember-320.814dbf35f7.jpg",
    "small": "ember-1600.3e98f48925.jpg",
    "large": "ember-2880.c04d2c4045.jpg"
  },
  {
    "id": "deep-sea",
    "name": "Deep sea",
    "category": "gradient",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#112F39",
    "luminance": 0.026,
    "thumb": "deep-sea-320.84cb9f011f.jpg",
    "small": "deep-sea-1600.864dd2837d.jpg",
    "large": "deep-sea-2880.4dddb5f975.jpg"
  },
  {
    "id": "dawn-haze",
    "name": "Dawn haze",
    "category": "gradient",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#EEE3DE",
    "luminance": 0.783,
    "thumb": "dawn-haze-320.1f4ec05006.jpg",
    "small": "dawn-haze-1600.7ddca122f5.jpg",
    "large": "dawn-haze-2880.5424369fd6.jpg"
  },
  {
    "id": "mist",
    "name": "Mist",
    "category": "gradient",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#E3E7EB",
    "luminance": 0.797,
    "thumb": "mist-320.39ae803c61.jpg",
    "small": "mist-1600.b165d6b60b.jpg",
    "large": "mist-2880.5f29795238.jpg"
  },
  {
    "id": "paper",
    "name": "Paper",
    "category": "texture",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#EEE9DF",
    "luminance": 0.818,
    "thumb": "paper-320.7347e8093a.jpg",
    "small": "paper-1600.4c3416b353.jpg",
    "large": "paper-2880.44c94738d4.jpg"
  },
  {
    "id": "linen",
    "name": "Linen",
    "category": "texture",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#E6E0D4",
    "luminance": 0.751,
    "thumb": "linen-320.e6a96c5b5b.jpg",
    "small": "linen-1600.85ca5caa4d.jpg",
    "large": "linen-2880.021171e9b2.jpg"
  },
  {
    "id": "watercolour",
    "name": "Watercolour",
    "category": "texture",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#EAE5DE",
    "luminance": 0.79,
    "thumb": "watercolour-320.44e48ff1d4.jpg",
    "small": "watercolour-1600.6eefc7970f.jpg",
    "large": "watercolour-2880.fed2787112.jpg"
  },
  {
    "id": "plaster",
    "name": "Plaster",
    "category": "texture",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#E7E2DC",
    "luminance": 0.764,
    "thumb": "plaster-320.4634c48a7d.jpg",
    "small": "plaster-1600.4bc1c1efd7.jpg",
    "large": "plaster-2880.45ec453988.jpg"
  },
  {
    "id": "contours",
    "name": "Contours",
    "category": "contour",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#1A1E26",
    "luminance": 0.013,
    "thumb": "contours-320.69a0963f33.jpg",
    "small": "contours-1600.86ec20bc74.jpg",
    "large": "contours-2880.792e03e9fe.jpg"
  },
  {
    "id": "charted",
    "name": "Charted",
    "category": "contour",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#1E231F",
    "luminance": 0.016,
    "thumb": "charted-320.30c62b75cf.jpg",
    "small": "charted-1600.89f27b93e4.jpg",
    "large": "charted-2880.98c0b9f9dc.jpg"
  },
  {
    "id": "survey",
    "name": "Survey",
    "category": "contour",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#EDE9E0",
    "luminance": 0.821,
    "thumb": "survey-320.b1478e4a78.jpg",
    "small": "survey-1600.b416f0d364.jpg",
    "large": "survey-2880.62a3d04ea0.jpg"
  },
  {
    "id": "bauhaus",
    "name": "Bauhaus",
    "category": "geometric",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#27272A",
    "luminance": 0.028,
    "thumb": "bauhaus-320.7d0b71b1e0.jpg",
    "small": "bauhaus-1600.d4932125b3.jpg",
    "large": "bauhaus-2880.0774227c8a.jpg"
  },
  {
    "id": "terrazzo",
    "name": "Terrazzo",
    "category": "geometric",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#EBE6E0",
    "luminance": 0.799,
    "thumb": "terrazzo-320.788e96385e.jpg",
    "small": "terrazzo-1600.fcb924f705.jpg",
    "large": "terrazzo-2880.dd6c2f93ef.jpg"
  },
  {
    "id": "grid",
    "name": "Grid",
    "category": "geometric",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#171B22",
    "luminance": 0.011,
    "thumb": "grid-320.aeb7d1645e.jpg",
    "small": "grid-1600.e155b0f730.jpg",
    "large": "grid-2880.acdf7f5736.jpg"
  },
  {
    "id": "hills",
    "name": "Hills",
    "category": "landscape",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 58
    },
    "color": "#1B2927",
    "luminance": 0.02,
    "thumb": "hills-320.bcf7fdd077.jpg",
    "small": "hills-1600.31acbd34ed.jpg",
    "large": "hills-2880.9a940322f6.jpg"
  },
  {
    "id": "dunes",
    "name": "Dunes",
    "category": "landscape",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 58
    },
    "color": "#E6DBCB",
    "luminance": 0.721,
    "thumb": "dunes-320.383dfa9b3b.jpg",
    "small": "dunes-1600.9ee922de6f.jpg",
    "large": "dunes-2880.0404a7e79a.jpg"
  },
  {
    "id": "dawn-sky",
    "name": "Dawn sky",
    "category": "landscape",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#EAE1D9",
    "luminance": 0.762,
    "thumb": "dawn-sky-320.56f236d200.jpg",
    "small": "dawn-sky-1600.a7f33a4bff.jpg",
    "large": "dawn-sky-2880.526a7d68a2.jpg"
  },
  {
    "id": "dusk-sky",
    "name": "Dusk sky",
    "category": "landscape",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "focal": {
      "x": 50,
      "y": 55
    },
    "color": "#241C2E",
    "luminance": 0.017,
    "thumb": "dusk-sky-320.4f36126538.jpg",
    "small": "dusk-sky-1600.6c7b26d07f.jpg",
    "large": "dusk-sky-2880.d7054b77a6.jpg"
  },
  {
    "id": "autumn",
    "name": "Autumn",
    "category": "seasonal",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#241D18",
    "luminance": 0.014,
    "thumb": "autumn-320.8feaaf7df0.jpg",
    "small": "autumn-1600.9ee2413c49.jpg",
    "large": "autumn-2880.4c94dd6bf0.jpg"
  },
  {
    "id": "winter",
    "name": "Winter",
    "category": "seasonal",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "focal": {
      "x": 50,
      "y": 56
    },
    "color": "#E0E6EC",
    "luminance": 0.788,
    "thumb": "winter-320.c9266f5308.jpg",
    "small": "winter-1600.9735495d1f.jpg",
    "large": "winter-2880.c3eb8a19ef.jpg"
  },
  {
    "id": "spring",
    "name": "Spring",
    "category": "seasonal",
    "tone": "light",
    "themes": [
      "household",
      "almanac",
      "blueprint"
    ],
    "color": "#ECE9DF",
    "luminance": 0.817,
    "thumb": "spring-320.9270899b9a.jpg",
    "small": "spring-1600.a8e579157c.jpg",
    "large": "spring-2880.a631a2e35d.jpg"
  },
  {
    "id": "summer",
    "name": "Summer",
    "category": "seasonal",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#1C3945",
    "luminance": 0.04,
    "thumb": "summer-320.f14da12172.jpg",
    "small": "summer-1600.5d6bcc7039.jpg",
    "large": "summer-2880.9f288165e1.jpg"
  },
  {
    "id": "confetti",
    "name": "Confetti",
    "category": "fun",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#1C1924",
    "luminance": 0.012,
    "thumb": "confetti-320.d820fa5f4d.jpg",
    "small": "confetti-1600.99b84e130e.jpg",
    "large": "confetti-2880.320a53c57d.jpg"
  },
  {
    "id": "night-sky",
    "name": "Night sky",
    "category": "fun",
    "tone": "dark",
    "themes": [
      "panels",
      "swiss"
    ],
    "color": "#11162C",
    "luminance": 0.009,
    "thumb": "night-sky-320.91a333fd75.jpg",
    "small": "night-sky-1600.985787cc34.jpg",
    "large": "night-sky-2880.12d3327bb6.jpg"
  }
] as const;
