/**
 * What each bundled wallpaper shows through Glass (plan item M4.2): its lightest
 * and darkest patch, blurred and saturated as Glass draws it. GENERATED by
 * `scripts/wallpapers/glass.mjs` from the shipped 1600px files — run it again
 * after the pictures change; do not edit this file. `file` is the content-hashed
 * name it was measured from, so `browser-wallpaper-glass.test.ts` knows at once
 * when a picture has been redrawn and this has not. `bare` is the same blocks
 * unblurred and unsaturated (plan item M4.7), what a Strong wash is solved from.
 */
export const WALLPAPER_GLASS: Readonly<
  Record<string, { readonly file: string; readonly light: string; readonly dark: string; readonly bare?: { readonly light: string; readonly dark: string } }>
> = {
  'dusk': { file: 'dusk-1600.1fb6019ff3.jpg', light: '#FF6110', dark: '#151036', bare: { light: '#F76B31', dark: '#15112C' } },
  'midnight': { file: 'midnight-1600.087621749b.jpg', light: '#00A6D4', dark: '#050C28', bare: { light: '#049ABB', dark: '#070C20' } },
  'ember': { file: 'ember-1600.0cc948b2d1.jpg', light: '#FF8313', dark: '#220608', bare: { light: '#F08A39', dark: '#1C0809' } },
  'deep-sea': { file: 'deep-sea-1600.77de008ea3.jpg', light: '#00BE8D', dark: '#001B28', bare: { light: '#00AE8B', dark: '#051923' } },
  'dawn-haze': { file: 'dawn-haze-1600.4e001cd0b0.jpg', light: '#FFE8DF', dark: '#FFBAD3', bare: { light: '#FCE9E3', dark: '#F5C0DA' } },
  'mist': { file: 'mist-1600.3599094480.jpg', light: '#D3F7FF', dark: '#CAD4FF', bare: { light: '#DBF5FE', dark: '#CCD5FD' } },
  'paper': { file: 'paper-1600.4c3416b353.jpg', light: '#F6F0E3', dark: '#EBE3D1', bare: { light: '#F4F0E7', dark: '#E9E3D6' } },
  'linen': { file: 'linen-1600.85ca5caa4d.jpg', light: '#EEE5D7', dark: '#E3DBC7', bare: { light: '#ECE5DB', dark: '#E1DBCD' } },
  'watercolour': { file: 'watercolour-1600.6eefc7970f.jpg', light: '#F5EEE2', dark: '#D2D1C3', bare: { light: '#F3EEE5', dark: '#D3D1C8' } },
  'plaster': { file: 'plaster-1600.4bc1c1efd7.jpg', light: '#ECE6DD', dark: '#E0DCD2', bare: { light: '#EBE6E0', dark: '#DFDCD5' } },
  'contours': { file: 'contours-1600.86ec20bc74.jpg', light: '#252C39', dark: '#161C27', bare: { light: '#282E37', dark: '#181C24' } },
  'charted': { file: 'charted-1600.89f27b93e4.jpg', light: '#282D24', dark: '#19221C', bare: { light: '#2A2D27', dark: '#1B211D' } },
  'survey': { file: 'survey-1600.b416f0d364.jpg', light: '#F1EBDE', dark: '#DDD7CA', bare: { light: '#EFEBE2', dark: '#DBD7CE' } },
  'bauhaus': { file: 'bauhaus-1600.d4932125b3.jpg', light: '#88804D', dark: '#1D1E24', bare: { light: '#857F5B', dark: '#1D1E22' } },
  'terrazzo': { file: 'terrazzo-1600.fcb924f705.jpg', light: '#EFE8DF', dark: '#D3C6CA', bare: { light: '#EDE8E2', dark: '#CFC5C9' } },
  'grid': { file: 'grid-1600.e155b0f730.jpg', light: '#1F324E', dark: '#161A24', bare: { light: '#25344A', dark: '#171A21' } },
  'hills': { file: 'hills-1600.31acbd34ed.jpg', light: '#1C3932', dark: '#0F201D', bare: { light: '#223732', dark: '#131F1D' } },
  'dunes': { file: 'dunes-1600.9ee922de6f.jpg', light: '#F0E8D7', dark: '#DEC7A4', bare: { light: '#EEE8DC', dark: '#D8C8AF' } },
  'dawn-sky': { file: 'dawn-sky-1600.a7f33a4bff.jpg', light: '#F8EDDD', dark: '#F5DABF', bare: { light: '#F6EDE4', dark: '#DDDEE6' } },
  'dusk-sky': { file: 'dusk-sky-1600.6c7b26d07f.jpg', light: '#7B3A41', dark: '#0F0B14', bare: { light: '#6D3E43', dark: '#0E0B12' } },
  'autumn': { file: 'autumn-1600.9ee2413c49.jpg', light: '#663E15', dark: '#1D1610', bare: { light: '#5E4022', dark: '#1B1612' } },
  'winter': { file: 'winter-1600.9735495d1f.jpg', light: '#E4EBF4', dark: '#D3E0E9', bare: { light: '#E6EBF1', dark: '#D6DFE6' } },
  'spring': { file: 'spring-1600.a8e579157c.jpg', light: '#F4F0E3', dark: '#E6C7C5', bare: { light: '#F3F0E7', dark: '#DFC9C7' } },
  'summer': { file: 'summer-1600.5d6bcc7039.jpg', light: '#B47E2A', dark: '#032A3B', bare: { light: '#A68044', dark: '#0C2834' } },
  'confetti': { file: 'confetti-1600.99b84e130e.jpg', light: '#4B3B25', dark: '#151322', bare: { light: '#4B3F2D', dark: '#15131E' } },
  'night-sky': { file: 'night-sky-1600.985787cc34.jpg', light: '#212A54', dark: '#080C21', bare: { light: '#242B49', dark: '#090C1B' } },
  'moonlit-bridge': { file: 'moonlit-bridge-1600.6f7933b8a5.jpg', light: '#BFA070', dark: '#14131A', bare: { light: '#B8A284', dark: '#141318' } },
  'sunset-woods': { file: 'sunset-woods-1600.c6f06b015b.jpg', light: '#EAA61C', dark: '#251E18', bare: { light: '#D8A745', dark: '#231E1A' } },
  'river-of-light': { file: 'river-of-light-1600.7abb58163c.jpg', light: '#F7E297', dark: '#1F1505', bare: { light: '#F2E2AC', dark: '#1B140A' } },
  'impending-storm': { file: 'impending-storm-1600.04cc9a3c1b.jpg', light: '#F2EAB7', dark: '#25161B', bare: { light: '#EFEAC6', dark: '#21161A' } },
  'keelmen': { file: 'keelmen-1600.765fd85c36.jpg', light: '#F9EBBD', dark: '#1B1B0D', bare: { light: '#F5EBCA', dark: '#1B1A11' } },
  'parliament': { file: 'parliament-1600.3189cc6a38.jpg', light: '#D2C888', dark: '#416E97', bare: { light: '#CFC7A9', dark: '#4C6B89' } },
  'waterloo-bridge': { file: 'waterloo-bridge-1600.8948e35b35.jpg', light: '#CAD6DF', dark: '#8299A1', bare: { light: '#CDD6DC', dark: '#88989D' } },
  'vetheuil-garden': { file: 'vetheuil-garden-1600.196061f812.jpg', light: '#FAC681', dark: '#1D5537', bare: { light: '#F0C996', dark: '#274F3A' } },
  'meadow': { file: 'meadow-1600.38689db454.jpg', light: '#D8CC9F', dark: '#0F4132', bare: { light: '#D7CDAC', dark: '#183D32' } },
  'port-en-bessin': { file: 'port-en-bessin-1600.30fe50f033.jpg', light: '#F2D492', dark: '#37351B', bare: { light: '#EBD4A9', dark: '#353422' } },
  'eragny-garden': { file: 'eragny-garden-1600.187f4341d3.jpg', light: '#E9E7D7', dark: '#2D4032', bare: { light: '#E8E8DC', dark: '#313F35' } },
  'cloud-study': { file: 'cloud-study-1600.4b99f7c4da.jpg', light: '#EADCB2', dark: '#856959', bare: { light: '#E8DDBF', dark: '#89655C' } },
  'beacon-rock': { file: 'beacon-rock-1600.fa08e0aea4.jpg', light: '#C1C78C', dark: '#371E0D', bare: { light: '#C1C69B', dark: '#311F13' } },
  'wijk-windmill': { file: 'wijk-windmill-1600.d255ee74ac.jpg', light: '#C8B388', dark: '#261B0D', bare: { light: '#C4B495', dark: '#231B11' } },
  'river-riders': { file: 'river-riders-1600.1cdf8cd631.jpg', light: '#F8E8BD', dark: '#231D15', bare: { light: '#F4E9CA', dark: '#211D17' } },
  'winter-skaters': { file: 'winter-skaters-1600.596ff47583.jpg', light: '#F4EBCF', dark: '#1F1D16', bare: { light: '#F2ECD8', dark: '#1C1B16' } },
  'merwede': { file: 'merwede-1600.c442faca41.jpg', light: '#F0C88E', dark: '#31291E', bare: { light: '#E6CAA0', dark: '#2F2920' } },
  'july-windmill': { file: 'july-windmill-1600.ec2d2aafc2.jpg', light: '#E8D6B0', dark: '#3C342B', bare: { light: '#E4D7BB', dark: '#38322C' } },
  'zwijndrecht-winter': { file: 'zwijndrecht-winter-1600.7504fb1b20.jpg', light: '#DBCEAD', dark: '#5D5B52', bare: { light: '#DACEAC', dark: '#5A5954' } },
  'orbital-sunset': { file: 'orbital-sunset-1600.6c6a4363d0.jpg', light: '#C6ECF5', dark: '#03040A', bare: { light: '#CFEAF2', dark: '#030408' } },
  'green-aurora': { file: 'green-aurora-1600.c68c97ae18.jpg', light: '#AEEE48', dark: '#0F0E0D', bare: { light: '#BEEB73', dark: '#0F0E0D' } },
  'night-lights': { file: 'night-lights-1600.da9dcfb54f.jpg', light: '#F8CEAF', dark: '#030103', bare: { light: '#FAD3AC', dark: '#030102' } },
  'westerlund': { file: 'westerlund-1600.ef295145f5.jpg', light: '#EBD1CC', dark: '#040B0E', bare: { light: '#E5D4D0', dark: '#050B0A' } },
  'bubble-nebula': { file: 'bubble-nebula-1600.c26b4b00bf.jpg', light: '#BFBEE5', dark: '#22081D', bare: { light: '#C0C0DC', dark: '#1C0A19' } },
  'butterfly-nebula': { file: 'butterfly-nebula-1600.c513ebead7.jpg', light: '#DBC8E6', dark: '#030303', bare: { light: '#D9CBE1', dark: '#030303' } },
  'cosmic-cliffs': { file: 'cosmic-cliffs-1600.9e4cd877df.jpg', light: '#D0B2AA', dark: '#17121B', bare: { light: '#CCB6B0', dark: '#11131A' } },
  'pillars-webb': { file: 'pillars-webb-1600.e44c1a4f88.jpg', light: '#C3C191', dark: '#240102', bare: { light: '#C4C29D', dark: '#1B0204' } },
  'rho-ophiuchi': { file: 'rho-ophiuchi-1600.941dd32585.jpg', light: '#F3F3D4', dark: '#080A0A', bare: { light: '#F3F4DE', dark: '#090A0A' } },
};
