import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { join } from 'node:path';
import { withLock } from './lock.js';
import type { SqliteDatabase } from './open.js';

/**
 * Migrations, run on boot, behind a file lock.
 *
 * Forward-only and generated by drizzle-kit. Once a migration has shipped it is
 * never edited: somebody's kitchen calendar has already applied it, and there
 * is no mechanism — and no person on site — to undo a rewrite.
 *
 * The governing constraint is rule nine. A failed migration must not stop the
 * process from starting. A wall display that boots and says "the calendar is
 * out of date, here is why" is recoverable; one that exit-codes into a restart
 * loop shows a black rectangle to a family who cannot read the logs.
 */

export type MigrationOutcome =
  /** Schema is current. Normal path. */
  | { readonly status: 'current'; readonly reclaimedLock: boolean }
  /** Could not take the lock. Another process is presumably migrating. */
  | { readonly status: 'locked'; readonly holder: string }
  /** Migration threw. The process continues in a degraded state. */
  | { readonly status: 'failed'; readonly error: string };

export interface MigrateOptions {
  readonly dataDir: string;
  /** Defaults to `<packageRoot>/migrations`. */
  readonly migrationsFolder: string;
  /** Passed through to the lock; tests shorten it. */
  readonly waitTimeoutMs?: number;
}

export function lockPath(dataDir: string): string {
  return join(dataDir, '.migrate.lock');
}

/**
 * Bring the schema up to date.
 *
 * Never throws. Every outcome is a value the boot sequence can report on
 * screen, because that is the only channel to a household that has no terminal.
 */
export function runMigrations(db: SqliteDatabase, options: MigrateOptions): MigrationOutcome {
  const path = lockPath(options.dataDir);

  const held = withLock(
    path,
    (): MigrationOutcome => {
      try {
        migrate(drizzle(db), { migrationsFolder: options.migrationsFolder });
        return { status: 'current', reclaimedLock: false };
      } catch (error) {
        return {
          status: 'failed',
          error: error instanceof Error ? error.message : 'unknown migration error',
        };
      }
    },
    {
      purpose: 'migrate',
      ...(options.waitTimeoutMs !== undefined ? { waitTimeoutMs: options.waitTimeoutMs } : {}),
    },
  );

  if (!held.ok) {
    const holder = held.holder;
    return {
      status: 'locked',
      holder: holder ? `pid ${holder.pid} on ${holder.host}` : 'an unidentified process',
    };
  }

  // Surface a reclaimed lock: it means a previous run died mid-migration, which
  // is worth knowing about even when this run succeeded.
  return held.value.status === 'current'
    ? { status: 'current', reclaimedLock: held.reclaimed }
    : held.value;
}

/**
 * A message for the on-screen banner.
 *
 * Written for whoever is standing in the kitchen, not for a log reader: it says
 * what is wrong and what still works, and never mentions a stack trace.
 */
export function describeOutcome(outcome: MigrationOutcome): string | undefined {
  switch (outcome.status) {
    case 'current':
      return outcome.reclaimedLock
        ? 'Recovered from an interrupted update. Everything is up to date.'
        : undefined;
    case 'locked':
      return (
        'Another copy of Maverick Wall is updating the database ' +
        `(${outcome.holder}). Showing the last known calendar until it finishes.`
      );
    case 'failed':
      return (
        'The database could not be updated, so some features may be missing. ' +
        'Your calendar is still being shown from its last sync.'
      );
    default:
      return undefined;
  }
}
