/**
 * The wall's bundled emoji artwork (D6, plan item P4.2).
 *
 * The image ships no emoji font, so an emoji set as *text* is a third-party
 * asset resolved on the device — a tablet draws its vendor's cartoon, the
 * tablet beside it draws a different vendor's, and some kiosks draw an empty
 * box. `no-emoji.test.ts` used to ban emoji everywhere a screen renders for
 * exactly that reason; D6 (2026-09-24) narrows the ban to the e-paper
 * renderer, because the image ships a curated Twemoji set under
 * `apps/server/assets/emoji/` instead — the same picture on every browser
 * wall, same-origin, served from `/assets/emoji/<key>.svg`.
 *
 * What travels through a widget's config and this module's own API is a
 * **key**, never a code point: `EMOJI_KEYS` is the whole vocabulary a designed
 * style may draw from, the way `GLYPH_KEYS` is for the closed icon set. A key
 * a bundle does not recognise draws nothing, the `glyphNode` rule, rather than
 * a broken image or the raw string.
 *
 * `apps/server/src/emoji.ts` transcribes the two blocks below character for
 * character — `emoji-parity.test.ts` compares them as text, the seam
 * `glyph-parity.test.ts` already sits at, for the reason it sits there: two
 * copies of one vocabulary is this project's most repeated bug.
 *
 * Text a household typed itself — a countdown's own title — renders in the
 * device's own font (Q9) and is untouched by this module: it is their string,
 * and the wall does not rewrite it.
 */

export const EMOJI_KEYS = [
  // Sky and weather conditions.
  'sun',
  'moon-crescent',
  'full-moon',
  'partly-cloudy-day',
  'cloud',
  'sun-behind-large-cloud',
  'sun-behind-rain-cloud',
  'cloud-with-rain',
  'cloud-with-lightning',
  'thunderstorm',
  'cloud-with-snow',
  'snowflake',
  'snowman',
  'snowman-without-snow',
  'fog',
  'wind-face',
  'tornado',
  'rainbow',
  'umbrella-with-rain-drops',
  'droplet',
  'sweat-droplets',
  'thermometer',
  // Advice-line pictures. Umbrella and wind are the weather set's own.
  'wind',
  'coat',
  'shorts',
  'sunscreen',
  // Occasions (D3): the six the countdown widget's occasion picker names.
  'christmas-tree',
  'birthday-cake',
  'jack-o-lantern',
  'beach-umbrella',
  'school-satchel',
  'fireworks',
  // The Store's hourglass (P1.1), and its counterpart.
  'hourglass',
  'hourglass-done',
  // A general picker: celebrations, travel, life events, sport, school, nature, animals and entertainment.
  'party-popper',
  'confetti-ball',
  'balloon',
  'gift',
  'sparkles',
  'star',
  'glowing-star',
  'trophy',
  'medal-1st-place',
  'medal-military',
  'ribbon',
  'red-heart',
  'two-hearts',
  'sparkling-heart',
  'heart-with-arrow',
  'revolving-hearts',
  'shortcake',
  'pizza',
  'popcorn',
  'bottle-with-popping-cork',
  'clinking-glasses',
  'cocktail-glass',
  'hot-beverage',
  'airplane',
  'car',
  'luggage',
  'palm-tree',
  'mountain',
  'camping',
  'ship',
  'world-map',
  'compass',
  'bride-with-veil',
  'ring',
  'baby',
  'baby-bottle',
  'graduation-cap',
  'house',
  'key',
  'briefcase',
  'package',
  'soccer-ball',
  'basketball',
  'american-football',
  'baseball',
  'tennis',
  'volleyball',
  'bowling',
  'books',
  'pencil',
  'leaf-fallen',
  'maple-leaf',
  'cherry-blossom',
  'sunflower',
  'four-leaf-clover',
  'tulip',
  'rose',
  'dog-face',
  'cat-face',
  'rabbit-face',
  'turkey',
  'baby-chick',
  'bird',
  'butterfly',
  'movie-camera',
  'ticket',
  'admission-tickets',
  'musical-note',
  'microphone',
  'video-game',
  'game-die',
  'artist-palette',
  'direct-hit',
  'alarm-clock',
  'calendar',
  'spiral-calendar',
  'white-check-mark',
  'sparkler',
  'candle',
  'light-bulb',
  'partying-face',
  'smiling-face-with-sunglasses',
  'clapping-hands',
  'raised-hands',
  'thumbs-up',
  'muscle',
  'crown',
  'gem-stone',
  'money-bag',
  'dollar-banknote',
  'rocket',
  'earth-globe-americas',
  'sunrise',
  'sunset',
  'star-struck',
  'santa',
  'bell',
  'reindeer',
  'ferris-wheel',
  'roller-coaster',
  'circus-tent',
  'performing-arts',
  'diploma-scroll',
  'credit-card',
  'shopping-bags',
  'high-voltage',
  'cyclone',
  'closed-umbrella',
  'ice-cream',
  'watermelon',
  'sunglasses',
  'apple-fruit',
  'ruler',
  'heart-eyes',
  'gift-heart',
  'handshake',
  'waving-hand',
  'paw-prints',
  'deciduous-tree',
  'evergreen-tree',
  'kiss-mark',
] as const;

export type EmojiKey = (typeof EMOJI_KEYS)[number];

/**
 * Whether a string names a bundled emoji. Used at every boundary a key
 * crosses: a widget's stored config and the store catalogue at build time.
 */
export function isEmojiKey(value: unknown): value is EmojiKey {
  return typeof value === 'string' && (EMOJI_KEYS as readonly string[]).includes(value);
}

const LABELS: Readonly<Record<EmojiKey, string>> = {
  'sun': 'Sun',
  'moon-crescent': 'Crescent moon',
  'full-moon': 'Full moon',
  'partly-cloudy-day': 'Sun behind cloud',
  'cloud': 'Cloud',
  'sun-behind-large-cloud': 'Sun behind large cloud',
  'sun-behind-rain-cloud': 'Sun behind rain cloud',
  'cloud-with-rain': 'Cloud with rain',
  'cloud-with-lightning': 'Cloud with lightning',
  'thunderstorm': 'Thunderstorm',
  'cloud-with-snow': 'Cloud with snow',
  'snowflake': 'Snowflake',
  'snowman': 'Snowman',
  'snowman-without-snow': 'Snowman without snow',
  'fog': 'Fog',
  'wind-face': 'Wind',
  'tornado': 'Tornado',
  'rainbow': 'Rainbow',
  'umbrella-with-rain-drops': 'Umbrella with rain drops',
  'droplet': 'Droplet',
  'sweat-droplets': 'Sweat droplets',
  'thermometer': 'Thermometer',
  'wind': 'Blowing gust',
  'coat': 'Coat',
  'shorts': 'Shorts',
  'sunscreen': 'Sunscreen',
  'christmas-tree': 'Christmas tree',
  'birthday-cake': 'Birthday cake',
  'jack-o-lantern': 'Jack-o-lantern',
  'beach-umbrella': 'Beach with umbrella',
  'school-satchel': 'School satchel',
  'fireworks': 'Fireworks',
  'hourglass': 'Hourglass, not done',
  'hourglass-done': 'Hourglass done',
  'party-popper': 'Party popper',
  'confetti-ball': 'Confetti ball',
  'balloon': 'Balloon',
  'gift': 'Wrapped gift',
  'sparkles': 'Sparkles',
  'star': 'Star',
  'glowing-star': 'Glowing star',
  'trophy': 'Trophy',
  'medal-1st-place': '1st place medal',
  'medal-military': 'Military medal',
  'ribbon': 'Ribbon',
  'red-heart': 'Red heart',
  'two-hearts': 'Two hearts',
  'sparkling-heart': 'Sparkling heart',
  'heart-with-arrow': 'Heart with arrow',
  'revolving-hearts': 'Revolving hearts',
  'shortcake': 'Shortcake',
  'pizza': 'Pizza',
  'popcorn': 'Popcorn',
  'bottle-with-popping-cork': 'Bottle with popping cork',
  'clinking-glasses': 'Clinking glasses',
  'cocktail-glass': 'Cocktail glass',
  'hot-beverage': 'Hot beverage',
  'airplane': 'Airplane',
  'car': 'Car',
  'luggage': 'Luggage',
  'palm-tree': 'Palm tree',
  'mountain': 'Mountain',
  'camping': 'Camping',
  'ship': 'Ship',
  'world-map': 'World map',
  'compass': 'Compass',
  'bride-with-veil': 'Person with veil',
  'ring': 'Ring',
  'baby': 'Baby',
  'baby-bottle': 'Baby bottle',
  'graduation-cap': 'Graduation cap',
  'house': 'House',
  'key': 'Key',
  'briefcase': 'Briefcase',
  'package': 'Package',
  'soccer-ball': 'Soccer ball',
  'basketball': 'Basketball',
  'american-football': 'American football',
  'baseball': 'Baseball',
  'tennis': 'Tennis',
  'volleyball': 'Volleyball',
  'bowling': 'Bowling',
  'books': 'Books',
  'pencil': 'Pencil',
  'leaf-fallen': 'Fallen leaf',
  'maple-leaf': 'Maple leaf',
  'cherry-blossom': 'Cherry blossom',
  'sunflower': 'Sunflower',
  'four-leaf-clover': 'Four leaf clover',
  'tulip': 'Tulip',
  'rose': 'Rose',
  'dog-face': 'Dog face',
  'cat-face': 'Cat face',
  'rabbit-face': 'Rabbit face',
  'turkey': 'Turkey',
  'baby-chick': 'Baby chick',
  'bird': 'Bird',
  'butterfly': 'Butterfly',
  'movie-camera': 'Movie camera',
  'ticket': 'Ticket',
  'admission-tickets': 'Admission tickets',
  'musical-note': 'Musical note',
  'microphone': 'Microphone',
  'video-game': 'Video game',
  'game-die': 'Game die',
  'artist-palette': 'Artist palette',
  'direct-hit': 'Direct hit',
  'alarm-clock': 'Alarm clock',
  'calendar': 'Calendar',
  'spiral-calendar': 'Spiral calendar',
  'white-check-mark': 'Check mark',
  'sparkler': 'Sparkler',
  'candle': 'Candle',
  'light-bulb': 'Light bulb',
  'partying-face': 'Partying face',
  'smiling-face-with-sunglasses': 'Smiling face with sunglasses',
  'clapping-hands': 'Clapping hands',
  'raised-hands': 'Raised hands',
  'thumbs-up': 'Thumbs up',
  'muscle': 'Flexed biceps',
  'crown': 'Crown',
  'gem-stone': 'Gem stone',
  'money-bag': 'Money bag',
  'dollar-banknote': 'Dollar banknote',
  'rocket': 'Rocket',
  'earth-globe-americas': 'Globe showing Americas',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset over buildings',
  'star-struck': 'Star-struck face',
  'santa': 'Santa Claus',
  'bell': 'Bell',
  'reindeer': 'Deer',
  'ferris-wheel': 'Ferris wheel',
  'roller-coaster': 'Roller coaster',
  'circus-tent': 'Circus tent',
  'performing-arts': 'Performing arts',
  'diploma-scroll': 'Scroll',
  'credit-card': 'Credit card',
  'shopping-bags': 'Shopping bags',
  'high-voltage': 'High voltage',
  'cyclone': 'Cyclone',
  'closed-umbrella': 'Closed umbrella',
  'ice-cream': 'Soft ice cream',
  'watermelon': 'Watermelon',
  'sunglasses': 'Sunglasses',
  'apple-fruit': 'Red apple',
  'ruler': 'Straight ruler',
  'heart-eyes': 'Heart eyes face',
  'gift-heart': 'Heart with ribbon',
  'handshake': 'Handshake',
  'waving-hand': 'Waving hand',
  'paw-prints': 'Paw prints',
  'deciduous-tree': 'Deciduous tree',
  'evergreen-tree': 'Evergreen tree',
  'kiss-mark': 'Kiss mark',
};

/**
 * One emoji as an `<img>`, or `null` for a key with no artwork.
 *
 * An `<img>` rather than an inline SVG: the artwork is somebody else's
 * drawing (Twemoji, CC-BY 4.0 — see `apps/server/assets/emoji/LICENSES.md`),
 * where the closed glyph set is ours and inlines as a path. Same-origin,
 * `img-src 'self'` already permits it, and nothing here runs a script.
 *
 * `null` rather than an empty node is `glyphNode`'s rule: the caller decides,
 * and every caller decides the same way — draw nothing rather than a box with
 * no picture in it.
 */
export function emojiNode(key: unknown, className = ''): HTMLImageElement | null {
  if (!isEmojiKey(key)) return null;
  const img = document.createElement('img');
  img.src = `/assets/emoji/${key}.svg`;
  img.alt = LABELS[key];
  if (className !== '') img.className = className;
  return img;
}
